version: "3.5"
services:
  app:
    image: adriankubica/app4switch
    build:
      context: .
    ports:
      - 9000:8000
    volumes:
      - ./:/app
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=*****
      - POSTGRES_DB=switch
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=*****
      - POSTGRES_DB=switch
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
